require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CopysubsController do

  # This should return the minimal set of attributes required to create a valid
  # Copysub. As you add validations to Copysub, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "section_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CopysubsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all copysubs as @copysubs" do
      copysub = Copysub.create! valid_attributes
      get :index, {}, valid_session
      assigns(:copysubs).should eq([copysub])
    end
  end

  describe "GET show" do
    it "assigns the requested copysub as @copysub" do
      copysub = Copysub.create! valid_attributes
      get :show, {:id => copysub.to_param}, valid_session
      assigns(:copysub).should eq(copysub)
    end
  end

  describe "GET new" do
    it "assigns a new copysub as @copysub" do
      get :new, {}, valid_session
      assigns(:copysub).should be_a_new(Copysub)
    end
  end

  describe "GET edit" do
    it "assigns the requested copysub as @copysub" do
      copysub = Copysub.create! valid_attributes
      get :edit, {:id => copysub.to_param}, valid_session
      assigns(:copysub).should eq(copysub)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Copysub" do
        expect {
          post :create, {:copysub => valid_attributes}, valid_session
        }.to change(Copysub, :count).by(1)
      end

      it "assigns a newly created copysub as @copysub" do
        post :create, {:copysub => valid_attributes}, valid_session
        assigns(:copysub).should be_a(Copysub)
        assigns(:copysub).should be_persisted
      end

      it "redirects to the created copysub" do
        post :create, {:copysub => valid_attributes}, valid_session
        response.should redirect_to(Copysub.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved copysub as @copysub" do
        # Trigger the behavior that occurs when invalid params are submitted
        Copysub.any_instance.stub(:save).and_return(false)
        post :create, {:copysub => { "section_id" => "invalid value" }}, valid_session
        assigns(:copysub).should be_a_new(Copysub)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Copysub.any_instance.stub(:save).and_return(false)
        post :create, {:copysub => { "section_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested copysub" do
        copysub = Copysub.create! valid_attributes
        # Assuming there are no other copysubs in the database, this
        # specifies that the Copysub created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Copysub.any_instance.should_receive(:update).with({ "section_id" => "1" })
        put :update, {:id => copysub.to_param, :copysub => { "section_id" => "1" }}, valid_session
      end

      it "assigns the requested copysub as @copysub" do
        copysub = Copysub.create! valid_attributes
        put :update, {:id => copysub.to_param, :copysub => valid_attributes}, valid_session
        assigns(:copysub).should eq(copysub)
      end

      it "redirects to the copysub" do
        copysub = Copysub.create! valid_attributes
        put :update, {:id => copysub.to_param, :copysub => valid_attributes}, valid_session
        response.should redirect_to(copysub)
      end
    end

    describe "with invalid params" do
      it "assigns the copysub as @copysub" do
        copysub = Copysub.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Copysub.any_instance.stub(:save).and_return(false)
        put :update, {:id => copysub.to_param, :copysub => { "section_id" => "invalid value" }}, valid_session
        assigns(:copysub).should eq(copysub)
      end

      it "re-renders the 'edit' template" do
        copysub = Copysub.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Copysub.any_instance.stub(:save).and_return(false)
        put :update, {:id => copysub.to_param, :copysub => { "section_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested copysub" do
      copysub = Copysub.create! valid_attributes
      expect {
        delete :destroy, {:id => copysub.to_param}, valid_session
      }.to change(Copysub, :count).by(-1)
    end

    it "redirects to the copysubs list" do
      copysub = Copysub.create! valid_attributes
      delete :destroy, {:id => copysub.to_param}, valid_session
      response.should redirect_to(copysubs_url)
    end
  end

end
