require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CopysecsController do

  # This should return the minimal set of attributes required to create a valid
  # Copysec. As you add validations to Copysec, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "project_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CopysecsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all copysecs as @copysecs" do
      copysec = Copysec.create! valid_attributes
      get :index, {}, valid_session
      assigns(:copysecs).should eq([copysec])
    end
  end

  describe "GET show" do
    it "assigns the requested copysec as @copysec" do
      copysec = Copysec.create! valid_attributes
      get :show, {:id => copysec.to_param}, valid_session
      assigns(:copysec).should eq(copysec)
    end
  end

  describe "GET new" do
    it "assigns a new copysec as @copysec" do
      get :new, {}, valid_session
      assigns(:copysec).should be_a_new(Copysec)
    end
  end

  describe "GET edit" do
    it "assigns the requested copysec as @copysec" do
      copysec = Copysec.create! valid_attributes
      get :edit, {:id => copysec.to_param}, valid_session
      assigns(:copysec).should eq(copysec)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Copysec" do
        expect {
          post :create, {:copysec => valid_attributes}, valid_session
        }.to change(Copysec, :count).by(1)
      end

      it "assigns a newly created copysec as @copysec" do
        post :create, {:copysec => valid_attributes}, valid_session
        assigns(:copysec).should be_a(Copysec)
        assigns(:copysec).should be_persisted
      end

      it "redirects to the created copysec" do
        post :create, {:copysec => valid_attributes}, valid_session
        response.should redirect_to(Copysec.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved copysec as @copysec" do
        # Trigger the behavior that occurs when invalid params are submitted
        Copysec.any_instance.stub(:save).and_return(false)
        post :create, {:copysec => { "project_id" => "invalid value" }}, valid_session
        assigns(:copysec).should be_a_new(Copysec)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Copysec.any_instance.stub(:save).and_return(false)
        post :create, {:copysec => { "project_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested copysec" do
        copysec = Copysec.create! valid_attributes
        # Assuming there are no other copysecs in the database, this
        # specifies that the Copysec created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Copysec.any_instance.should_receive(:update).with({ "project_id" => "1" })
        put :update, {:id => copysec.to_param, :copysec => { "project_id" => "1" }}, valid_session
      end

      it "assigns the requested copysec as @copysec" do
        copysec = Copysec.create! valid_attributes
        put :update, {:id => copysec.to_param, :copysec => valid_attributes}, valid_session
        assigns(:copysec).should eq(copysec)
      end

      it "redirects to the copysec" do
        copysec = Copysec.create! valid_attributes
        put :update, {:id => copysec.to_param, :copysec => valid_attributes}, valid_session
        response.should redirect_to(copysec)
      end
    end

    describe "with invalid params" do
      it "assigns the copysec as @copysec" do
        copysec = Copysec.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Copysec.any_instance.stub(:save).and_return(false)
        put :update, {:id => copysec.to_param, :copysec => { "project_id" => "invalid value" }}, valid_session
        assigns(:copysec).should eq(copysec)
      end

      it "re-renders the 'edit' template" do
        copysec = Copysec.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Copysec.any_instance.stub(:save).and_return(false)
        put :update, {:id => copysec.to_param, :copysec => { "project_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested copysec" do
      copysec = Copysec.create! valid_attributes
      expect {
        delete :destroy, {:id => copysec.to_param}, valid_session
      }.to change(Copysec, :count).by(-1)
    end

    it "redirects to the copysecs list" do
      copysec = Copysec.create! valid_attributes
      delete :destroy, {:id => copysec.to_param}, valid_session
      response.should redirect_to(copysecs_url)
    end
  end

end
